/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.napaurban.napaurbandb.forms;

import com.napaurban.napaurbandb.dao.ClienteDao;
import com.napaurban.napaurbandb.dao.FacturaVentaDao;
import com.napaurban.napaurbandb.dao.PrendaDao;
import com.napaurban.napaurbandb.dao.TipoDePagoDao;
import com.napaurban.napaurbandb.dao.VendedoraDao;
import com.napaurban.napaurbandb.dao.VendidoDao;
import com.napaurban.napaurbandb.models.FacturaVenta;
import com.napaurban.napaurbandb.models.Prenda;
import com.napaurban.napaurbandb.models.TipoDePago;
import com.napaurban.napaurbandb.models.Vendedora;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 54113
 */
public class FormularioVenta extends javax.swing.JFrame {

    /**
     * Creates new form FormularioVenta
     */
    public FormularioVenta() {
        initComponents();
    }
    
    public String[] getIdArr() {
        String[] idArr = new String[10];
        //int idInt;
        String val = (String)this.txtIdPrenda.getText();
        String[] valArr = val.split("\\s+");
        int ii = 0;
        
        for(String idStr : valArr) {
            //idInt = Integer.parseInt(idStr);
            idArr[ii] = idStr;
            ii++;
        }
        return idArr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioFinal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TipoDePagoDao dao = new TipoDePagoDao();
        List<TipoDePago> listado = dao.listar();
        String[] tiposDePago = new String[6];
        int i = 0;
        Iterator<TipoDePago> iterador = listado.iterator();
        while(iterador.hasNext()) {
            TipoDePago tdp = iterador.next();
            tiposDePago[i] = tdp.getNombre();
            i++;
        }
        txtTipoDePago = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        VendedoraDao daoVND = new VendedoraDao();
        List<Vendedora> listadoVND = daoVND.listar();
        String[] vendedores = new String[15];
        final int[] h = {0};
        listadoVND.forEach(vendedora -> {
            vendedores[h[0]] = vendedora.getNombre();
            h[0]++;
        });
        txtVendedora = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        btnEmail = new javax.swing.JButton();
        btnPrenda = new javax.swing.JButton();
        txtPrecioPorUnidad = new javax.swing.JLabel();
        btnVender = new javax.swing.JButton();
        txtCantidad = new javax.swing.JLabel();
        txtIdPrenda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Precio por unidad:");

        jLabel2.setText("id-prenda:");

        jLabel3.setText("email cliente:");

        jLabel4.setText("Cantidad:");

        jLabel5.setText("Precio final:");

        txtPrecioFinal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtPrecioFinal.setText("0");

        jLabel6.setText("tipo de pago:");

        txtTipoDePago.setModel(new javax.swing.DefaultComboBoxModel(tiposDePago));

        jLabel7.setText("Vendedora:");

        txtVendedora.setModel(new javax.swing.DefaultComboBoxModel(vendedores));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnEmail.setText("Buscar");
        btnEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailActionPerformed(evt);
            }
        });

        btnPrenda.setText("Buscar");
        btnPrenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrendaActionPerformed(evt);
            }
        });

        txtPrecioPorUnidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtPrecioPorUnidad.setText("0");

        btnVender.setText("¡Vender!");
        btnVender.setEnabled(false);
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        txtCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtCantidad.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipoDePago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVendedora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(txtIdPrenda))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPrenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(3, 3, 3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecioPorUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrecioFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnPrenda)
                    .addComponent(txtPrecioPorUnidad)
                    .addComponent(txtIdPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEmail))
                    .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecioFinal)
                    .addComponent(jLabel6)
                    .addComponent(txtTipoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtVendedora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnVender)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmailActionPerformed
        ClienteDao clnDAO = new ClienteDao();
        int clnID = clnDAO.buscarPorEmail(this.txtEmail.getText());
        if (clnID != -1){
            JOptionPane.showMessageDialog(null,"¡Email encontrado!");
        } else {
            System.out.println("ERROR");
            JOptionPane.showMessageDialog(null, "No hemos encontrado el email :( ¡pero hemos creado uno en la DataBase! :D");
        }
    }//GEN-LAST:event_btnEmailActionPerformed

    private void btnPrendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrendaActionPerformed
        String val = (String)this.txtIdPrenda.getText();
        getIdArr();
        System.out.println(val);
        String[] valArr = val.split("\\s+");
        int[] prndPUArr = new int[10];
        String prndPUstr = new String();
        PrendaDao daoPRND = new PrendaDao();
        Prenda prnd = new Prenda();
        int prndPU;
        int prndFP = 0;
        int ii = 0;
        int c = 0;
        
        for(String idStr : valArr) {
            //int idInt = Integer.parseInt(idStr);
            prnd = daoPRND.buscarPorId(idStr);
            prndPU = prnd.getPrecioUnitario();
            prndPUArr[ii] = prndPU;
            ii++;
            prndPUstr += " "+prndPU;
            System.out.println(prndPUstr);
        }
        
        for(int prndPUint : prndPUArr) {
            prndFP += prndPUint;
            if (prndPUint != 0) {
                c++;
            }
        }
        
        this.txtPrecioPorUnidad.setText(String.valueOf(prndPUstr));
        this.txtCantidad.setText(String.valueOf(c));
        this.txtPrecioFinal.setText(String.valueOf(prndFP));
        if (String.valueOf(prndPUstr) != null) {
            this.btnVender.setEnabled(true);
        }
        
        
        
    }//GEN-LAST:event_btnPrendaActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        FacturaVentaDao daoF = new FacturaVentaDao();
        FacturaVenta fvta = new FacturaVenta();
        TipoDePagoDao daoT = new TipoDePagoDao();
        PrendaDao daoPr = new PrendaDao ();
        ClienteDao daoC = new ClienteDao();
        int idT = daoT.buscarIdPorNombre(this.txtTipoDePago.getSelectedItem().toString());
        VendedoraDao daoV = new VendedoraDao();
        int idV = daoV.buscarPorNombre(this.txtVendedora.getSelectedItem().toString());
        int idC = daoC.buscarPorEmail(this.txtEmail.getText());
        String[] idParr = getIdArr();
        int PU = 0;
        String str_c = this.txtCantidad.getText();
        int c = Integer.parseInt(str_c);
        String str_PF = this.txtPrecioFinal.getText();
        int PF = Integer.parseInt(str_PF);
        String nomP;
        
        for(String idP : idParr){
            if (idP != null){
                PU = daoPr.buscarPrecioUnitarioPorId(idP);
                nomP = daoPr.buscarNombrePorId(idP);
                System.out.println(PU);
                fvta.setIdCliente(idC);
                fvta.setNombreProducto(nomP);
                fvta.setPrecioUnitario(PU);
                fvta.setCantidad(c);
                fvta.setPrecioFinal(PF);
                fvta.setIdTipoDePago(idT);
                fvta.setIdVendedora(idV);
                daoF.agregar(fvta);
        
        
                
                
                VendidoDao daoVen = new VendidoDao();
                PrendaDao daoPren = new PrendaDao();
                Prenda prenda = new Prenda();
                prenda = daoPren.buscarPorId(idP);
                daoVen.agregar(prenda);
                daoV.SumarVentas(idV, PF);
                daoPr.eliminar(idP);
                daoC.sumarCompra(idC);
                daoC.sumarGasto(idC, PF);
                if (daoPr.existeEsteId(idP)) {
                    JOptionPane.showMessageDialog(null, "Venta completada!");
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrió un error computando la venta :(");
                }
                }
                
            }
        
        
    }//GEN-LAST:event_btnVenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmail;
    private javax.swing.JButton btnPrenda;
    private javax.swing.JButton btnVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdPrenda;
    private javax.swing.JLabel txtPrecioFinal;
    private javax.swing.JLabel txtPrecioPorUnidad;
    private javax.swing.JComboBox<String> txtTipoDePago;
    private javax.swing.JComboBox<String> txtVendedora;
    // End of variables declaration//GEN-END:variables

    private TipoDePagoDao TipoDePagoDao() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private VendedoraDao VendedoraDao() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
